### ISSUE TITLE
Add support for vTPM

### ISSUE THREAD

**Issue by ibeerens** [hashicorp/packer-plugin-vmware#125]
Windows 11 requires a UEFI BIOS and TPM 2.0. Is it possible to add this to the vmware-iso builder?

**Comment by tenthirtyam** [comment]
I would suggest that this be split into two enhancement requests:
- UEFI (+ Secure Boot)
- TPM

**Comment by cwestwater** [comment]
For UEFI I do this:

```
  vmx_data = {
    "firmware"        = "efi"
  }
```

But TPM support is needed. I see the vsphere-iso plugin has it [available](https://developer.hashicorp.com/packer/plugins/builders/vsphere/vsphere-iso#vtpm)

**Comment by tenthirtyam** [comment]
Duplicate of #58

**Comment by tenthirtyam** [comment]
Limiting scope to vTPM.

**Comment by ChristoWolf** [comment]
Does this then enable support for Windows 11 VMs?

**Comment by ChristoWolf** [comment]
Hi @tenthirtyam!

Any news on this?

For visibility, I'm gonna leave [this potential work-around](https://github.com/andif888/packer-windows-vsphere-iso#windows-11---bypasstpmcheck), maybe it helps someone down the line.
Disclaimer: I have not tried this personally.

**Comment by tenthirtyam** [comment]
Hi @ChristoWolf - I don't have any plans to work on this any time soon.

I'm currently working on some technical debt across this plugin and the `vsphere` plugin and prioritizing accordingly based on my availability.

I've now placed all open issues into a milestone so that these can be tracked. If one if picked up, you'll see it moved to a version milestone.

**Comment by tenthirtyam** [comment]
Duplicate of #110
